# Generated by Django 3.1.1 on 2020-09-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('blood_group', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
