# Generated by Django 3.1.1 on 2020-09-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood',
            name='additional_info',
            field=models.CharField(default='', max_length=255),
        ),
    ]
